theme: jekyll-theme-minimal
# Site settings
title: Li Huang           
SEOTitle: Li          # 在后面会详细谈到
description: "Research Asisitant in School of Data and Computer Science (SDCS), Sun Yat-sen University (SYSU)"    # 随便说点，描述一下


